name: post_app_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  firebase_storage: ^10.3.7
  flutterfire_ui: ^0.4.3+7
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  shared_preferences: ^2.0.15
  firebase_auth: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
