// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBVs5ZkAd3c7rpXQZWZ_-JhRicD-zlZbI',
    appId: '1:948483912198:web:3b03dec68e8a8453efc987',
    messagingSenderId: '948483912198',
    projectId: 'postappdemo',
    authDomain: 'postappdemo.firebaseapp.com',
    storageBucket: 'postappdemo.appspot.com',
    measurementId: 'G-T0VJ2TD02C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ldBFX8W_oAdZ_iC3UH5cgHTnB7yi8io',
    appId: '1:948483912198:android:50466074b4830786efc987',
    messagingSenderId: '948483912198',
    projectId: 'postappdemo',
    storageBucket: 'postappdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbDfNDUuYFW9LrQVQaGTWl04WGFH7w2Ro',
    appId: '1:948483912198:ios:da16f7ebacecc0ceefc987',
    messagingSenderId: '948483912198',
    projectId: 'postappdemo',
    storageBucket: 'postappdemo.appspot.com',
    iosClientId: '948483912198-ucag4mj6cl3lbehbhi56j2sp94m55fmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.postAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbDfNDUuYFW9LrQVQaGTWl04WGFH7w2Ro',
    appId: '1:948483912198:ios:da16f7ebacecc0ceefc987',
    messagingSenderId: '948483912198',
    projectId: 'postappdemo',
    storageBucket: 'postappdemo.appspot.com',
    iosClientId: '948483912198-ucag4mj6cl3lbehbhi56j2sp94m55fmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.postAppDemo',
  );
}
